services:
  web:
    build: .
    volumes:
      - .:/app
      - ./data/db:/var/lib/postgresql/data
      - ./alembic.ini:/alembic.ini
    ports:
      - "8000:8000"
    networks:
      - my_shared_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Ocacine10#@postgres:5432/fastapi"
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    stdin_open: true  # Equivalent to 'docker run -i'
    tty: true         # Equivalent to 'docker run -t'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Ocacine10#"
      POSTGRES_DB: "fastapi"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: false
